### ISSUE TITLE
Passenger API - Changes a flag on the authenticated User

### ISSUE THREAD

**Issue by ans-ioki** [ioki-mobility/ioki-ruby#3]
Hmm. Looking at the docs it seems to me that we already have a way to set flags for a user with Update the authenticated User. The description says only one flag is allowed but schema and example say all three flags are supported.

It seems to me that the flags endpoint is being phased out. Is that correct? Or is that the one that should be used? Or are there separate use cases for both? 🤔

@ans-ioki Can you clarify this for me? So far I'd say we can just add the two missing flags to the existing update a user endpoint and call it a day.

**Comment by A5308Y** [comment]
We suspect this is outdated so we're closing this.
