### ISSUE TITLE
VCR::Errors due to mismatch in API_BASE_URL in test setup

### ISSUE THREAD

**Issue by eikes** [ioki-mobility/ioki-ruby#31]
I just cloned this repository and noticed that the `spec/ioki/vcr` tests all failed with similar messages:

     VCR::Errors::UnhandledHTTPRequestError:

       ================================================================================
       An HTTP request has been made that VCR does not know how to handle:
         GET https://app.io.ki/api/platform/providers

The reason seems to be, that in the `spec/fixtures/vcr_cassettes` files the `https://demo.io.ki/api/` API_BASE_URL is used, but this is not configured by default in the test setup where `https://app.io.ki/api/` is used.

I was able to fix this by exporting the appropriate ENV variables as it is done in the `.github/ci_workflow.env` file:

```
export IOKI_PLATFORM_API_BASE_URL="https://demo.io.ki/api/"
export IOKI_PASSENGER_API_BASE_URL="https://demo.io.ki/api/" 
export IOKI_DRIVER_API_BASE_URL="https://demo.io.ki/api/"
```

This should be documented somewhere or maybe simply use the `https://app.io.ki/api/` API_BASE_URL in the VCR files as well and remove these ENV vars from the CI setup? Or set the ENV variable in the `spec_helper.rb` file?

**Comment by eikes** [comment]
Setting the env variable in the spec helper was the simplest:

```ruby
ENV['IOKI_PLATFORM_API_BASE_URL']  ||= "https://demo.io.ki/api/"
ENV['IOKI_PASSENGER_API_BASE_URL'] ||= "https://demo.io.ki/api/"
ENV['IOKI_DRIVER_API_BASE_URL']    ||= "https://demo.io.ki/api/"
```

**Comment by A5308Y** [comment]
Sounds good @eikes. Can you prepare a PR for this?

**Comment by A5308Y** [comment]
@eikes Could you let me know about any other issue you have/had while setting up?
https://github.com/ioki-mobility/ioki-ruby/issues/20 is still on my list and your perspective would be very helpful here.
