### ISSUE TITLE
Retry on failure

### ISSUE THREAD

**Issue by eikes** [ioki-mobility/ioki-ruby#72]
Despite the API being very stable I have seen the occasional 500 error and I would like to make the client more stable by retrying failed requests before giving up. This will be particularly helpful for large index requests. We could make use of the faraday-retry middleware for this scenario:

https://github.com/lostisland/faraday-retry

**Comment by tom-ioki** [comment]
Yes, pretty please 🙏

**Comment by eikes** [comment]
I haven't seen any timeouts anymore. So I'd be fine with not doing this.
