### ISSUE TITLE
PlatformApi: Add Place Endpoints

### ISSUE THREAD

**Issue by tom-ioki** [ioki-mobility/ioki-ruby#85]
As mentioned in the title. `ioki-ruby` lacks the endpoints for the `Place` model. These endpoints should be added.

**Comment by eikes** [comment]
According to the docs these endpoints don't exist in the API

**Comment by tom-ioki** [comment]
Not yet! But there is already a PR ready for review for triebwerk :)

**Comment by ans-ioki** [comment]
They've been merged on triebwerks side.

**Comment by eikes** [comment]
Done in df66b7a764981bb99b3ae326c9815355d93ee9a8
